module.exports = {
  DECK_SIZE: 52,
  TOP_CARD: 12,
  STARTING_VALUE: 4,
  STARTING_SUIT: 'Clubs',
  VALUE_TO_CARD_MAP: {
    0: 4,
    1: 5,
    2: 6,
    3: 7,
    4: 8,
    5: 9,
    6: 10,
    7: 'J',
    8: 'Q',
    9: 'K',
    10: 'A',
    11: 2,
    12: 3,
  },
  CARD_TO_VALUE_MAP: {
    4: 0,
    5: 1,
    6: 2,
    7: 3,
    8: 4,
    9: 5,
    10: 6,
    J: 7,
    Q: 8,
    K: 9,
    A: 10,
    2: 11,
    3: 12,
  },
  SUITS: ['Clubs', 'Diamonds', 'Hearts', 'Spades'],
  SUIT_MAP: {
    C: 'Clubs',
    D: 'Diamonds',
    H: 'Hearts',
    S: 'Spades',
  },
  SPECIAL_RANKS: ['Jack', 'Queen', 'King', 'Ace'],
  SUIT_EMOJIS_MAP: {
    Clubs: '♣️',
    Diamonds: '♦️',
    Hearts: '♥️',
    Spades: '♠️',
  },
};
